name: Run Cypress Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: npm install

      - name: Servir app (com live-server)
        run: |
          npm install -g live-server
          live-server frontend --port=5500 &
          sleep 5

      - name: Rodar testes Cypress
        env:
          BASE_URL: http://127.0.0.1:5500  # 👈 baseUrl para o Cypress rodar no Actions
        run: npx cypress run
